### ISSUE TITLE
Premium accourt - Strategy backtesting

### ISSUE THREAD

**Issue by defiNature** [Mathieu2301/TradingView-API#96] opened 2022-05-13 12:32 UTC
Strategy backtesting don't use all the candle of premium account

I can give you my crendentials to test

**Comment by defiNature** [comment] 2022-05-13 13:00
const chart = new client.Session.Chart();
  chart.setMarket('BINANCE:BTCEUR', {
    timeframe: '60', range: 10000
  });

not orking

**Comment by brandonros** [comment] 2022-07-24 21:05
duplicate of https://github.com/Mathieu2301/TradingView-API/issues/90, any movement?

**Comment by Mathieu2301** [comment] 2022-07-24 21:16
I fixed it last week !
Use the prodata server when you create the Client.

**Comment by brandonros** [comment] 2022-07-24 21:18
> prodata

thank you!

not only that, I found this (I think from you):

https://www.tradingview.com/support/solutions/43000480679-i-can-t-see-all-historical-data-on-resolutions-lower-than-1-day/

**Comment by brandonros** [comment] 2022-07-24 21:19
https://github.com/Mathieu2301/TradingView-API/blob/9451ffff5b032276e2f6af504773d4689f1373f9/src/client.js#L227

for anybody falling along, thanks Mathieu

**Closed** 2022-07-24 21:28 UTC
Labels: bug
