### ISSUE TITLE
Credentials error: Wrong or expired sessionid

### ISSUE THREAD

**Issue by 0xR-Dev** [Mathieu2301/TradingView-API#187] opened 2023-04-14 10:52 UTC
did the code still working?

im trying some example there but showing error

"Credentials error: Wrong or expired sessionid"

im have to put correct token id, but still get the error.
anyone can help to solve it?

**Comment by RudySM-hub** [comment] 2023-04-14 12:45
im try using this code 

`const TradingView = require("@mathieuc/tradingview");


if (!process.argv[2]) throw Error('Please specify your \'sessionid\' cookie');

const client = new TradingView.Client({
  token: process.argv[2],
});

const chart = new client.Session.Chart();
chart.setMarket('BINANCE:BTCEUR', {
  timeframe: 'D',
});

TradingView.getPrivateIndicators(process.argv[2]).then((indicList) => {
  indicList.forEach(async (indic) => {
    const privateIndic = await indic.get();
    console.log('Loading indicator', indic.name, '...');

    const indicator = new chart.Study(privateIndic);

    indicator.onReady(() => {
      console.log('Indicator', indic.name, 'loaded !');
    });

    indicator.onUpdate(() => {
      console.log('Plot values', indicator.periods);
      console.log('Strategy report', indicator.strategyReport);
    });
  });
});`

and output :

`Loading indicator EMA 20/50/100/200 ...
Credentials error: Wrong or expired sessionid`

**Comment by daniil-dn** [comment] 2023-04-14 17:38
The same problem

**Comment by hawooni** [comment] 2023-04-14 23:34
It seems that we also need to include the sessionid_sign.

**Comment by hyjay** [comment] 2023-04-14 23:41
Same issue here. Seems like TradingView has made a breaking change.

**Comment by hawooni** [comment] 2023-04-14 23:45
temporary, if you include "sessionid=${session};sessionid_sign={YOUR_VALUE};" in miscRequests.js line 408 should work.

**Comment by hyjay** [comment] 2023-04-14 23:48
> temporary, if you include "sessionid=${session};sessionid_sign={YOUR_VALUE};" in miscRequests.js line 408 should work.

+1. It works.

**Comment by RudySM-hub** [comment] 2023-04-15 04:00
> temporary, if you include "sessionid=${session};sessionid_sign={YOUR_VALUE};" in miscRequests.js line 408 should work.

Thanks its, worked now..

**Comment by kyr0** [comment] 2023-04-15 16:55
Also, username/password based login still works well. At least with the most recent version via github 

```

  "dependencies": {
    "@mathieuc/tradingview": "github:Mathieu2301/TradingView-API",
  }
```

**Comment by lordbritish888** [comment] 2023-04-17 13:51
How can I use your method without it disconnecting my browser TradingView? @kyr0 

I still get the same error with this code.. @0xR-Dev @hawooni 

```
sign = "v1:j6C5uAzIpQcAfHIUMhyFESRrKWCeO/fv/mt+4qRRPsE="
  async getUser(session, location = 'https://www.tradingview.com/') {
    return new Promise((cb, err) => {
      https.get(location, {
        headers: { cookie: `sessionid=${session};sessionid_sign=${sign}` },
```

**Comment by lordbritish888** [comment] 2023-04-17 13:51
I got the sessionid and the sessionid_sign from the browser on an already logged in instance of TradingView

**Comment by hawooni** [comment] 2023-04-17 14:04
Shameless plug here. I am using this to fetch my TradingView Snapshot API data. https://doc.chart-img.com

**Comment by lordbritish888** [comment] 2023-04-17 14:12
@hawooni it still isn't working :/

I even tried this:

const clientTV = new TradingView.Client({
  token: process.argv[2],
  session: process.argv[2],
  sessionid_sign: "v1:j6C5uAzIpQcAfHIUMhyFESRrKWCeO/fv/mt+4qRRPsE="
});

**Comment by lordbritish888** [comment] 2023-04-17 14:13
@Mathieu2301 can you patch this please? or can anyone provide an updated miscRequests.js with corresponding login via token example?

**Comment by hawooni** [comment] 2023-04-17 14:18
> @hawooni it still isn't working :/
> 
> I even tried this:
> 
> const clientTV = new TradingView.Client({ token: process.argv[2], session: process.argv[2], sessionid_sign: "v1:j6C5uAzIpQcAfHIUMhyFESRrKWCeO/fv/mt+4qRRPsE=" });

Hard code the value sessionid_sign directly as mentioned above as this is just a temporary solution.

**Comment by lordbritish888** [comment] 2023-04-17 14:21
@hawooni The user/password method disconnects the browser session :/

are you using the vi: part or just the part after for signing?

**Comment by lordbritish888** [comment] 2023-04-17 14:26
@hawooni it works well, just you cannot use TV in your browser while its running and re-logging in on browser disconnects the NodeJS session :/

**Comment by lordbritish888** [comment] 2023-04-17 15:06
@0xR-Dev does your sign look like this? 

sign = "v1:j6C5uAzIpQcAfHIUMhyFESRrKWCeO/fv/mt+4qRRPsE="

**Comment by lordbritish888** [comment] 2023-04-17 16:33
After the log in method was mostly good, I'm now getting this..

`Login error: Please confirm that you are not a robot by clicking the captcha box
.`

**Comment by amayp1** [comment] 2023-04-17 21:38
> temporary, if you include "sessionid=${session};sessionid_sign={YOUR_VALUE};" in miscRequests.js line 408 should work.

I have replaced line 408 to like this but I still encounter the credentials error ?

        headers: { cookie: `sessionid=${session};sessionid_sign={v1:Ms/DU43561uJEfjdkbJPrz1GDBNLrl6YTIpmDY=};` },

**Comment by hawooni** [comment] 2023-04-17 21:51
> > temporary, if you include "sessionid=${session};sessionid_sign={YOUR_VALUE};" in miscRequests.js line 408 should work.
> 
> I have replaced line 408 to like this but I still encounter the credentials error ?
> 
> ```
>     headers: { cookie: `sessionid=${session};sessionid_sign={v1:Ms/DU43561uJEfjdkbJPrz1GDBNLrl6YTIpmDY=};` },
> ```

your value should be without {} => ...cookie: `sessionid=${session};sessionid_sign=v1:Ms/DU43561uJEfjdkbJPrz1GDBNLrl6YTIpmDY=;`},

**Comment by amayp1** [comment] 2023-04-17 22:55
> > > temporary, if you include "sessionid=${session};sessionid_sign={YOUR_VALUE};" in miscRequests.js line 408 should work.
> > 
> > 
> > I have replaced line 408 to like this but I still encounter the credentials error ?
> > ```
> >     headers: { cookie: `sessionid=${session};sessionid_sign={v1:Ms/DU43561uJEfjdkbJPrz1GDBNLrl6YTIpmDY=};` },
> > ```
> 
> your value should be without {} =>
 ...`sessionid=${session};sessionid_sign=v1:Ms/DU43561uJEfjdkbJPrz1GDBNLrl6YTIpmDY=;`},





> 

I tried it but then it gives me this error. Do we nee do make changes in other files?

TypeError: str.replace is not a function
    at Object.parseWSPacket ←[90m(C:\Users\Administrator\←[39mDesktop\STTradingstrat\TradingView-API-main\src\protocol.js:20:16←[90m)←[39m
    at #parsePacket ←[90m(C:\Users\Administrator\←[39mDesktop\STTradingstrat\TradingView-API-main\src\client.js:160:14←[90m)←[39m
    at WebSocket.<anonymous> ←[90m(C:\Users\Administrator\←[39mDesktop\STTradingstrat\TradingView-API-main\src\client.js:262:55←[90m)←[39m
←[90m    at WebSocket.emit (node:events:513:28)←[39m
    at Receiver.receiverOnMessage ←[90m(C:\Users\Administrator\←[39mnode_modules\←[4mws←[24m\lib\websocket.js:1184:20←[90m)←[39m
←[90m    at Receiver.emit (node:events:513:28)←[39m
    at Receiver.dataMessage ←[90m(C:\Users\Administrator\←[39mnode_modules\←[4mws←[24m\lib\receiver.js:541:14←[90m)←[39m
    at ←[90mC:\Users\Administrator\←[39mnode_modules\←[4mws←[24m\lib\receiver.js:492:23
    at ←[90mC:\Users\Administrator\←[39mnode_modules\←[4mws←[24m\lib\permessage-deflate.js:309:9
    at ←[90mC:\Users\Administrator\←[39mnode_modules\←[4mws←[24m\lib\permessage-deflate.js:392:7

Node.js v19.9.0

**Comment by hawooni** [comment] 2023-04-17 22:59
> > > > temporary, if you include "sessionid=${session};sessionid_sign={YOUR_VALUE};" in miscRequests.js line 408 should work.
> > > 
> > > 
> > > I have replaced line 408 to like this but I still encounter the credentials error ?
> > > ```
> > >     headers: { cookie: `sessionid=${session};sessionid_sign={v1:Ms/DU43561uJEfjdkbJPrz1GDBNLrl6YTIpmDY=};` },
> > > ```
> > 
> > 
> > your value should be without {} =>
> > ...`sessionid=${session};sessionid_sign=v1:Ms/DU43561uJEfjdkbJPrz1GDBNLrl6YTIpmDY=;`},
> 
> > 
> 
> I tried it but then it gives me this error. Do we nee do make changes in other files?
> 
> TypeError: str.replace is not a function at Object.parseWSPacket ←[90m(C:\Users\Administrator\←[39mDesktop\STTradingstrat\TradingView-API-main\src\protocol.js:20:16←[90m)←[39m at #parsePacket ←[90m(C:\Users\Administrator\←[39mDesktop\STTradingstrat\TradingView-API-main\src\client.js:160:14←[90m)←[39m at WebSocket. ←[90m(C:\Users\Administrator\←[39mDesktop\STTradingstrat\TradingView-API-main\src\client.js:262:55←[90m)←[39m ←[90m at WebSocket.emit (node:events:513:28)←[39m at Receiver.receiverOnMessage ←[90m(C:\Users\Administrator\←[39mnode_modules\←[4mws←[24m\lib\websocket.js:1184:20←[90m)←[39m ←[90m at Receiver.emit (node:events:513:28)←[39m at Receiver.dataMessage ←[90m(C:\Users\Administrator\←[39mnode_modules\←[4mws←[24m\lib\receiver.js:541:14←[90m)←[39m at ←[90mC:\Users\Administrator\←[39mnode_modules\←[4mws←[24m\lib\receiver.js:492:23 at ←[90mC:\Users\Administrator\←[39mnode_modules\←[4mws←[24m\lib\permessage-deflate.js:309:9 at ←[90mC:\Users\Administrator\←[39mnode_modules\←[4mws←[24m\lib\permessage-deflate.js:392:7
> 
> Node.js v19.9.0

try again with nodejs18

**Comment by amayp1** [comment] 2023-04-17 23:06
> > > > > temporary, if you include "sessionid=${session};sessionid_sign={YOUR_VALUE};" in miscRequests.js line 408 should work.
> > > > 
> > > > 
> > > > I have replaced line 408 to like this but I still encounter the credentials error ?
> > > > ```
> > > >     headers: { cookie: `sessionid=${session};sessionid_sign={v1:Ms/DU43561uJEfjdkbJPrz1GDBNLrl6YTIpmDY=};` },
> > > > ```
> > > 
> > > 
> > > your value should be without {} =>
> > > ...`sessionid=${session};sessionid_sign=v1:Ms/DU43561uJEfjdkbJPrz1GDBNLrl6YTIpmDY=;`},
> > 
> > 
> > > 
> > 
> > 
> > I tried it but then it gives me this error. Do we nee do make changes in other files?
> > TypeError: str.replace is not a function at Object.parseWSPacket ←[90m(C:\Users\Administrator\←[39mDesktop\STTradingstrat\TradingView-API-main\src\protocol.js:20:16←[90m)←[39m at #parsePacket ←[90m(C:\Users\Administrator\←[39mDesktop\STTradingstrat\TradingView-API-main\src\client.js:160:14←[90m)←[39m at WebSocket. ←[90m(C:\Users\Administrator\←[39mDesktop\STTradingstrat\TradingView-API-main\src\client.js:262:55←[90m)←[39m ←[90m at WebSocket.emit (node:events:513:28)←[39m at Receiver.receiverOnMessage ←[90m(C:\Users\Administrator\←[39mnode_modules\←[4mws←[24m\lib\websocket.js:1184:20←[90m)←[39m ←[90m at Receiver.emit (node:events:513:28)←[39m at Receiver.dataMessage ←[90m(C:\Users\Administrator\←[39mnode_modules\←[4mws←[24m\lib\receiver.js:541:14←[90m)←[39m at ←[90mC:\Users\Administrator\←[39mnode_modules\←[4mws←[24m\lib\receiver.js:492:23 at ←[90mC:\Users\Administrator\←[39mnode_modules\←[4mws←[24m\lib\permessage-deflate.js:309:9 at ←[90mC:\Users\Administrator\←[39mnode_modules\←[4mws←[24m\lib\permessage-deflate.js:392:7
> > Node.js v19.9.0
> 
> try again with nodejs18

Still same error


C:\Users\Administrator\Desktop\STTradingstrat\TradingView-API-main\src\protocol.js:20
    return str.replace(cleanerRgx, '').split(splitterRgx)
               ^

TypeError: str.replace is not a function
    at Object.parseWSPacket ←[90m(C:\Users\Administrator\←[39mDesktop\STTradingstrat\TradingView-API-main\src\protocol.js:20:16←[90m)←[39m
    at #parsePacket ←[90m(C:\Users\Administrator\←[39mDesktop\STTradingstrat\TradingView-API-main\src\client.js:160:14←[90m)←[39m
    at WebSocket.<anonymous> ←[90m(C:\Users\Administrator\←[39mDesktop\STTradingstrat\TradingView-API-main\src\client.js:262:55←[90m)←[39m
←[90m    at WebSocket.emit (node:events:513:28)←[39m
    at Receiver.receiverOnMessage ←[90m(C:\Users\Administrator\←[39mnode_modules\←[4mws←[24m\lib\websocket.js:1184:20←[90m)←[39m
←[90m    at Receiver.emit (node:events:513:28)←[39m
    at Receiver.dataMessage ←[90m(C:\Users\Administrator\←[39mnode_modules\←[4mws←[24m\lib\receiver.js:541:14←[90m)←[39m
    at ←[90mC:\Users\Administrator\←[39mnode_modules\←[4mws←[24m\lib\receiver.js:492:23
    at ←[90mC:\Users\Administrator\←[39mnode_modules\←[4mws←[24m\lib\permessage-deflate.js:309:9
    at ←[90mC:\Users\Administrator\←[39mnode_modules\←[4mws←[24m\lib\permessage-deflate.js:392:7

Node.js v18.16.0

**Comment by lordbritish888** [comment] 2023-04-17 23:17
The login with user/pass (when it doesn't require a captcha which it sometimes does) is now working for basic chart.  However, the private indicators will not load.  This appears to have changed today?

**Comment by amayp1** [comment] 2023-04-17 23:22
Is anyone able to get private indicator data?

**Comment by lordbritish888** [comment] 2023-04-17 23:25
@amayp1 I am not able to right now.  I am none of the people who offered solutions have shown examples of the fix with the sessionid_sign but that seems to be the only way since credentials login is not serving the data.

**Comment by amayp1** [comment] 2023-04-17 23:31
Join this server.  

https://discord.gg/C6z6praC

**Comment by Mathieu2301** [comment] 2023-04-22 17:24
Hi everyone!
I can't reproduce the bug described in this issue.
I have tested the `getUser`, `getPrivateIndicators` methods, and I have also tried to create a TradingView client:

```js
const client = new TradingView.Client({
  token: process.env.SESSION,
});
```

then added the user's indicators one by one.

I didn't have any problems and didn't need to include `sessionid_sign`.
I am using the latest version from GitHub.

I added a new automated test for these authenticated methods. I created a TradingView account for the occasion.
You can find the code of this test here: https://github.com/Mathieu2301/TradingView-API/blob/main/tests/10.%20Authenticated.js
You can find the results of the last tests here: https://github.com/Mathieu2301/TradingView-API/actions/runs/4773889220

I don't recommend abusing the `loginUser` method because it creates a new session every time it is called. Go to https://www.tradingview.com/u/YOUR_USERNAME/#security in the "PRIVACY AND SECURITY" tab to see the list of active sessions.

Can someone give me more information about the bug described in this issue? Thanks 😊

**Comment by hawooni** [comment] 2023-04-24 17:51
> Hi everyone! I can't reproduce the bug described in this issue. I have tested the `getUser`, `getPrivateIndicators` methods, and I have also tried to create a TradingView client:
> 
> ```js
> const client = new TradingView.Client({
>   token: process.env.SESSION,
> });
> ```
> 
> then added the user's indicators one by one.
> 
> I didn't have any problems and didn't need to include `sessionid_sign`. I am using the latest version from GitHub.
> 
> I added a new automated test for these authenticated methods. I created a TradingView account for the occasion. You can find the code of this test here: https://github.com/Mathieu2301/TradingView-API/blob/main/tests/10.%20Authenticated.js You can find the results of the last tests here: https://github.com/Mathieu2301/TradingView-API/actions/runs/4773889220
> 
> I don't recommend abusing the `loginUser` method because it creates a new session every time it is called. Go to https://www.tradingview.com/u/YOUR_USERNAME/#security in the "PRIVACY AND SECURITY" tab to see the list of active sessions.
> 
> Can someone give me more information about the bug described in this issue? Thanks 😊

I tested it, and it appears that the sessionid_sign is no longer required. Thx :)

**Comment by msitarz** [comment] 2023-04-25 05:33
@gasparesganga Your issue with indicator limit might be due to TV simply using anonymous session rather than logged in because you didn't provide `sessionid_sign` properly. I had problem with using various timeframes from my pro account when I didn't provide `sessionid_sign`.

@Mathieu2301 can you check again if you are logged in properly without using the sign parameter and then using some pro account features like second timeframes?

I already created a patch but only on my local copy and I'm using version 3.3.3. I'll test with the newest version and I'll provide pull request when I have a bit of time so you guys can check.

**Comment by gasparesganga** [comment] 2023-04-25 06:05
@msitarz This is not the case. As I wrote, it seems TV is now ignoring whether we provide a `sessionid_sign` or not. I am providing a valid `sessionid_sign` anyways, but this new issue does not depend on it. It happens even using just `loginUser` and no session at all.
Are you able to get data for more than 3 indicators/studies at the same time?

@Mathieu2301 In the meanwhile I finished a patch to fully integrate `sessionid_sign` into v3.4.0. If it turns out it's still required, I can publish a rep and make a pull request. Or maybe I can add an option to turn this signature on and off? Your call!

**Comment by msitarz** [comment] 2023-04-25 06:34
@gasparesganga I've checked using the new version and code without `sessionid_sign` and indeed it works correctly. I don't have the issues with timeframes that I had before. I don't use indicators so I cannot tell you if I can use more than 3. 

It looks like tradingview tech team did some changes to their auth API previously and now they rolled it back.

**Comment by gasparesganga** [comment] 2023-04-26 13:11
Alright, the error I was getting was due to a silly mistake in my code. Everything is working great again without any `sessionid_sign`.
It does seem strange indeed that they added and quickly ditched it after a few days, but it is what is it.
In case it came back, I got a patch ready for it.

**Comment by sohaha** [comment] 2023-05-03 13:00
I would like to kindly inquire if anyone might be aware of the approximate duration before a session ID expires.

**Comment by zwarrior1** [comment] 2023-05-05 07:52
Hi everyone, I started writing a trading bot yesterday and I don't know whatever it is fixed or not, but made some changes just 
for temporary fix.


[examples/CustomTimeframe.js:10 ~ 14](https://github.com/Mathieu2301/TradingView-API/blob/main/examples/CustomTimeframe.js#L10)
``` JS
const client = new TradingView.Client({
  token: "z80k9g2eimw8k1lvvav649pvbt7p8ylw",
  sessionid_sign: "v1:y3Ub2hIFitGGxIMfZQE4iXVwHAPg/KNYR33vyqe7RQE="
});
```

[src/client.js:232 ~ 234](https://github.com/Mathieu2301/TradingView-API/blob/main/src/client.js#L232)
``` JS
if (clientOptions.token && clientOptions.sessionid_sign) {
      misc.getUser(clientOptions.token, clientOptions.sessionid_sign).then((user) => {
```



[src/miscRequests.js:405 ~ 443](https://github.com/Mathieu2301/TradingView-API/blob/main/src/miscRequests.js#L405)
``` JS
async getUser(sessionid, sessionid_sign='', location = 'https://www.tradingview.com/') {
    return new Promise((cb, err) => {
      https.get(location, {
        headers: { cookie: `sessionid=${sessionid}; sessionid_sign=${sessionid_sign}` },
      }, (res) => {
        let rs = '';
        res.on('data', (d) => { rs += d; });
        res.on('end', async () => {
          if (res.headers.location && location !== res.headers.location) {
            cb(await module.exports.getUser(sessionid, sessionid_sign, res.headers.location));
            return;
          }
          if (rs.includes('auth_token')) {
            cb({
              id: /"id":([0-9]{1,10}),/.exec(rs)[1],
              username: /"username":"(.*?)"/.exec(rs)[1],
              firstName: /"first_name":"(.*?)"/.exec(rs)[1],
              lastName: /"last_name":"(.*?)"/.exec(rs)[1],
              reputation: parseFloat(/"reputation":(.*?),/.exec(rs)[1] || 0),
              following: parseFloat(/,"following":([0-9]*?),/.exec(rs)[1] || 0),
              followers: parseFloat(/,"followers":([0-9]*?),/.exec(rs)[1] || 0),
              notifications: {
                following: parseFloat(/"notification_count":\{"following":([0-9]*),/.exec(rs)[1] || 0),
                user: parseFloat(/"notification_count":\{"following":[0-9]*,"user":([0-9]*)/.exec(rs)[1] || 0),
              },
              sessionid,
              sessionid_sign,
              sessionHash: /"session_hash":"(.*?)"/.exec(rs)[1],
              privateChannel: /"private_channel":"(.*?)"/.exec(rs)[1],
              authToken: /"auth_token":"(.*?)"/.exec(rs)[1],
              joinDate: new Date(/"date_joined":"(.*?)"/.exec(rs)[1] || 0),
            });
          } else err(new Error('Wrong or expired sessionid'));
        });

        res.on('error', err);
      }).end();
    });
  },
```

**Comment by gbarton** [comment] 2023-05-06 16:44
its clugy but I can do a bit of an injection to get the sessionid_sign into the sessionid I pass in and it works.  I use dotenv and just pass in whatever I have in my tv_token prop through to token, something like:
```
let client = new TradingView.Client({ token: process.env.tv_token });
```

for tv_token it looks like this:
```
# my token and sign are from the browser, make sure to use yours!
tv_token="mytokenfromthebrowser; sessionid_sign=v1:S6EadHXwm845QDfNn8PVygP7N5yyj4bXDE2MQ3eZg48="
```

and I'm running again.  Don't have to mod the src like above to make it work, but don't forget the quotes if your using props!

**Comment by Mathieu2301** [comment] 2023-05-06 20:50
Fixed it in v3.4.1 !
Thanks to all and thanks to Gaspare Sganga for his pull request #197 😁

I will close this issue if no one has a problem this week.

**Comment by amayp1** [comment] 2023-05-06 21:08
Mine is working fine now thanks guys :)

**Comment by mmaestrini** [comment] 2023-05-29 11:40
Can someone tell me what I am doing wrong then?

` TradingView.loginUser(
      process.env.TRADINGVIEW_EMAIL,
      process.env.TRADINGVIEW_PASSWORD,
      false,
    )
      .then((user) => {
        console.log('User:', user);
        console.log('Sessionid:', user.session);

        const client = new TradingView.Client({
          token: user.session,
        });

        const chart = new client.Session.Chart();
        chart.setTimezone('Europe/Copenhagen');

        const adapter = new TvApiAdapter();

        chart.setMarket('BYBIT:OPUSDT.P', {
          timeframe: '5M',
          range: 200,
        });

        TradingView.getDrawings(process.env.TRADINGVIEW_CHART_LAYOUT, null, {
          session: user.session,
          id: user.id,
        })
          .then((drawings) => {
            console.log(
              `Found ${drawings.length} drawings:`,
              drawings.map((d) => ({
                id: d.id,
                symbol: d.symbol,
                type: d.type,
                text: d.state.text,
              })),
            );
          })
          .catch((err) => {
            console.error('Error:', err.message);
          });
      })
      .catch((err) => {
        console.error('Login error:', err.message);
      });`

I am logging in and then I am asking the drawings passing my session, userId and chart layout ID. 

After successfully loggin in I get `Credentials error: Wrong or expired sessionid/signature` message, even tho I get a response in the "then" callback of the getdrawings (tho it returns an empty array).

Any help is appreciated.

**Closed** 2023-05-29 19:03 UTC
Labels: bug, help wanted, Important

**Comment by BlackPhoenixSlo** [comment] 2024-01-28 12:25
I started getting this error as I am running at the same time 3 or more scripts. 

I will chain them 1 by 1.

**Comment by BlackPhoenixSlo** [comment] 2024-01-28 12:31
<img width="1128" alt="Screenshot 2024-01-28 at 13 31 14" src="https://github.com/Mathieu2301/TradingView-API/assets/49908413/ddec021d-ed2d-4be8-97cf-2f7200b940af">
I am getting same problem.
